package:
    name: corpus-callosum-thickness
    version: "0.0.1"

source:
    git_url: https://bayers@bitbucket.org/bayers/ccshape.git
	
requirements:
    build:
        - python
    run:
        - python
        - numpy
        - shapeio
        - curvematch